GET http://localhost:3000/users

###

GET http://localhost:3000/users?limit=2&offset=2&order=oldest

###

GET http://localhost:3000/users/8dd2b0f1-726d-4d52-a88b-e8da1cff4a

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "yjkim@example.com",
  "firstName": "유진",
  "lastName": "김",
  "address": "충청북도 청주시 북문로 210번길 5",
  "userPreference": {
    "receiveEmail": false
  }
}

###

PATCH http://localhost:3000/users/73cb9639-d8b7-4f11-9a62-53f4187f3f11
Content-Type: application/json

{
  "email": "yjkim2@example.com",
  "userPreference": {
    "receiveEmail": true
  }
}

###

DELETE http://localhost:3000/users/3ca78837-8fc4-44f0-97ba-a38437ccc514

###

GET http://localhost:3000/users/3ca78837-8fc4-44f0-97ba-a38437ccc514/saved-products

